import { Person, GiftItem, HolidayDefinition } from './types';

export const INITIAL_PEOPLE: Person[] = [
  {
    id: 'person-1',
    name: 'Alex Chen',
    relationship: 'partner',
    birthMonth: 9,
    birthDay: 22,
    birthYear: 1996, // Turning 30 in 2026! Milestone
    avatarColor: '#fbcfe8', // pastel rose
    cuteFace: {
      expression: 'cool',
      hairStyle: 'beanie',
      hairColor: '#451a03',
      glasses: true,
      blush: true,
      accessory: 'beanie',
    },
    interests: ['Photography', 'Specialty Coffee', 'Hiking', 'Leathercraft'],
    sizes: {
      clothing: 'M / 38',
      shoe: '10.5 US',
      ring: 'Size 9',
      notes: 'Prefers earthy colors, minimalist aesthetic',
    },
    preferences: {
      likes: 'Single origin Ethiopian coffee, tactile notebooks, wool beanies',
      dislikes: 'Overly sweet scents, clutter',
      allergies: 'None',
      favoriteColors: 'Forest green, terracotta, warm taupe',
    },
    customEvents: [
      {
        id: 'event-anniv',
        name: 'Our 5th Anniversary',
        month: 10,
        day: 18,
        year: 2021,
      },
    ],
    annualBudget: 350,
    notes: 'Dropped a hint about wanting a custom hand-stitched camera strap or travel photo book.',
  },
  {
    id: 'person-2',
    name: 'Maya Miller',
    relationship: 'family',
    birthMonth: 9,
    birthDay: 14,
    birthYear: 1999, // Turning 27 (in 6 days!)
    avatarColor: '#ddd6fe', // pastel lilac
    cuteFace: {
      expression: 'sparkle',
      hairStyle: 'curly',
      hairColor: '#7c2d12',
      blush: true,
      accessory: 'flower',
    },
    interests: ['Ceramics', 'Indoor Plants', 'Baking Sourdough'],
    sizes: {
      clothing: 'S',
      shoe: '7 US',
      notes: 'Loves oversized sweaters and linen aprons',
    },
    preferences: {
      likes: 'Handmade pottery, matcha tea, heirloom flower seeds',
      dislikes: 'Plastic knick-knacks',
      allergies: 'Mild dust sensitivity',
      favoriteColors: 'Sage green, lilac',
    },
    annualBudget: 150,
    notes: 'Mentioned wanting a proofing basket or ceramic oil drizzler.',
  },
  {
    id: 'person-3',
    name: 'Elena Miller (Mom)',
    relationship: 'family',
    birthMonth: 10,
    birthDay: 12,
    birthYear: 1966, // Turning 60 milestone!
    avatarColor: '#fed7aa', // pastel peach
    cuteFace: {
      expression: 'gentle',
      hairStyle: 'wavy',
      hairColor: '#a8a29e',
      glasses: true,
      blush: true,
      accessory: 'none',
    },
    interests: ['Gardening', 'Cooking Italian cuisine', 'Watercolor painting'],
    sizes: {
      clothing: 'L',
      shoe: '8.5 US',
      notes: 'Prefers loose, breathable cotton and cozy shawls',
    },
    preferences: {
      likes: 'Lavender scents, fine olive oils, gardening shears, framed photos of kids',
      dislikes: 'Flashy electronics',
      allergies: 'Penicillin',
      favoriteColors: 'Warm burgundy, cream, lavender',
    },
    annualBudget: 200,
    notes: 'Big 60th birthday this October! We should do something sentimental.',
  },
  {
    id: 'person-4',
    name: 'Sam Rivera',
    relationship: 'friend',
    birthMonth: 11,
    birthDay: 5,
    birthYear: 1995,
    avatarColor: '#bae6fd', // pastel sky blue
    cuteFace: {
      expression: 'wink',
      hairStyle: 'short',
      hairColor: '#1e293b',
      freckles: true,
      blush: true,
      accessory: 'cap',
    },
    interests: ['Rock Climbing', 'Board Games', 'Sci-Fi Books'],
    sizes: {
      clothing: 'L',
      shoe: '11 US',
    },
    preferences: {
      likes: 'Specialty chalk bags, heavy strategy games, dark roast coffee',
      dislikes: 'Cheap novelty socks',
      allergies: 'None',
      favoriteColors: 'Cobalt blue, charcoal',
    },
    annualBudget: 80,
    notes: 'Talked about trying out that new space-themed worker placement board game.',
  },
  {
    id: 'person-5',
    name: 'Marcus Vance',
    relationship: 'colleague',
    birthMonth: 12,
    birthDay: 3,
    birthYear: 1990,
    avatarColor: '#bbf7d0', // pastel mint green
    cuteFace: {
      expression: 'grin',
      hairStyle: 'slick',
      hairColor: '#334155',
      glasses: true,
      blush: false,
      accessory: 'none',
    },
    interests: ['Mechanical Keyboards', 'Espresso', 'Tech gadgets'],
    sizes: {},
    preferences: {
      likes: 'Desk accessories, artisanal tea tins, coaster sets',
    },
    annualBudget: 50,
    notes: 'Great mentor on the team; keep it professional but thoughtful.',
  },
  {
    id: 'person-6',
    name: 'Chloe Zhao',
    relationship: 'friend',
    birthMonth: 6,
    birthDay: 18,
    birthYear: 1998,
    avatarColor: '#fef08a', // pastel lemon chiffon
    cuteFace: {
      expression: 'happy',
      hairStyle: 'bob',
      hairColor: '#1c1917',
      blush: true,
      accessory: 'bow',
    },
    interests: ['Yoga', 'Matcha Lattes', 'Film Photography', 'Thrifting'],
    sizes: {
      clothing: 'M',
      shoe: '8 US',
    },
    preferences: {
      likes: 'Ceramic mugs, vintage camera straps, organic herbal teas',
      dislikes: 'Single-use plastic items',
    },
    annualBudget: 75,
    notes: 'Birthday is in June (farther away, smaller bubble). Loves indie coffee shop gift cards.',
  },
];

export const INITIAL_GIFTS: GiftItem[] = [
  {
    id: 'gift-1',
    title: 'Hand-Stitched Italian Leather Camera Strap',
    recipientId: 'person-1',
    occasion: 'birthday',
    targetYear: 2026,
    type: 'handmade',
    status: 'in_progress',
    priority: 'high',
    estimatedPrice: 38,
    actualPrice: 35,
    craftingHoursEstimated: 6,
    craftingHoursSpent: 3.5,
    craftDifficulty: 'Medium',
    craftDeadline: '2026-09-20',
    craftSupplies: [
      { id: 'sup-1', name: 'Vegetable-tanned leather strip (1.5" wide)', estimatedCost: 22, purchased: true },
      { id: 'sup-2', name: 'Waxed linen thread (amber gold)', estimatedCost: 6, purchased: true },
      { id: 'sup-3', name: 'Brass buckle hardware & split rings', estimatedCost: 7, purchased: true },
      { id: 'sup-4', name: 'Edge beveler wax & burnisher', estimatedCost: 0, purchased: true }, // already owned
    ],
    craftSteps: [
      { id: 'st-1', text: 'Cut leather strap to 42" & round the tip edges', done: true, hours: 1 },
      { id: 'st-2', text: 'Bevel edges and slick with beeswax', done: true, hours: 1.5 },
      { id: 'st-3', text: 'Prick stitch holes with diamond chisel (in progress)', done: true, hours: 1 },
      { id: 'st-4', text: 'Saddle stitch brass hardware into place', done: false, hours: 1.5 },
      { id: 'st-5', text: 'Apply conditioning balm and stamp initials "A.C."', done: false, hours: 1 },
    ],
    notes: 'Alex loves film photography and has been using an old worn nylon strap. Leather will age beautifully.',
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'gift-2',
    title: 'Peak Design Wrist Cuff Quick-Release',
    recipientId: 'person-1',
    occasion: 'birthday',
    targetYear: 2026,
    type: 'bought',
    status: 'purchased',
    priority: 'medium',
    estimatedPrice: 35,
    actualPrice: 34.95,
    storeOrUrl: 'https://www.peakdesign.com',
    notes: 'Bought as a companion piece to the handmade strap so they have versatility on hikes.',
    createdAt: '2026-08-25T14:30:00Z',
  },
  {
    id: 'gift-3',
    title: 'Custom Glazed Ceramic Matcha Bowl with Bamboo Whisk',
    recipientId: 'person-2',
    occasion: 'birthday',
    targetYear: 2026,
    type: 'handmade',
    status: 'completed',
    priority: 'high',
    estimatedPrice: 20,
    actualPrice: 18.5,
    craftingHoursEstimated: 5,
    craftingHoursSpent: 5,
    craftDifficulty: 'Medium',
    craftDeadline: '2026-09-12',
    craftSupplies: [
      { id: 'sup-m1', name: 'Speckled stoneware clay', estimatedCost: 6, purchased: true },
      { id: 'sup-m2', name: 'Celadon sage food-safe glaze', estimatedCost: 8, purchased: true },
      { id: 'sup-m3', name: 'Authentic 100-prong bamboo chasen whisk', estimatedCost: 4.5, purchased: true },
    ],
    craftSteps: [
      { id: 'st-m1', text: 'Throw chawan bowl on pottery wheel with spout', done: true, hours: 1.5 },
      { id: 'st-m2', text: 'Trim foot ring and stamp maker mark', done: true, hours: 1 },
      { id: 'st-m3', text: 'Bisque fire at cone 04', done: true, hours: 0.5 },
      { id: 'st-m4', text: 'Apply celadon dip glaze and glaze fire at cone 6', done: true, hours: 1 },
      { id: 'st-m5', text: 'Sand base smooth and tie with linen string and whisk', done: true, hours: 1 },
    ],
    notes: 'Maya has been obsessed with making morning matcha! Finished and ready for Sunday!',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'gift-4',
    title: 'Vintage Botanical Watercolor Collection (6 Framed Prints)',
    recipientId: 'person-3',
    occasion: 'birthday',
    targetYear: 2026,
    type: 'handmade',
    status: 'planning',
    priority: 'high',
    estimatedPrice: 45,
    craftingHoursEstimated: 10,
    craftingHoursSpent: 1,
    craftDifficulty: 'Advanced',
    craftDeadline: '2026-10-08',
    craftSupplies: [
      { id: 'sup-b1', name: 'Archival 300gsm cold-press cotton watercolor paper', estimatedCost: 15, purchased: true },
      { id: 'sup-b2', name: 'Set of 6 natural oak 5x7" frames with mats', estimatedCost: 24, purchased: false },
      { id: 'sup-b3', name: 'Winsor & Newton watercolor pigments', estimatedCost: 0, purchased: true },
    ],
    craftSteps: [
      { id: 'st-b1', text: 'Select 6 of Mom\'s favorite garden herbs & flowers', done: true, hours: 1 },
      { id: 'st-b2', text: 'Pencil sketches and botanical accuracy check', done: false, hours: 2.5 },
      { id: 'st-b3', text: 'Layer watercolor washes (lavender, rosemary, sage, rose, chamomile, thyme)', done: false, hours: 4.5 },
      { id: 'st-b4', text: 'Fine pen ink lining and Latin botanical calligraphy', done: false, hours: 1.5 },
      { id: 'st-b5', text: 'Mount in oak frames with archival matting', done: false, hours: 1 },
    ],
    notes: 'Need to allocate 2-3 hours each weekend in late Sept so it\'s ready for her 60th birthday!',
    createdAt: '2026-08-28T16:00:00Z',
  },
  {
    id: 'gift-5',
    title: 'Clif Bar & Artisanal Chalk Bag + Climbing Hand Balm',
    recipientId: 'person-4',
    occasion: 'birthday',
    targetYear: 2026,
    type: 'bought',
    status: 'idea',
    priority: 'medium',
    estimatedPrice: 40,
    storeOrUrl: 'https://rei.com',
    notes: 'His current chalk bag is tearing at the seams. Look into Organic Climbing custom chalk bags.',
    createdAt: '2026-09-01T11:00:00Z',
  },
  {
    id: 'gift-6',
    title: 'Artisanal Batch Rosemary Sea-Salt Olive Oil Infusion',
    recipientId: 'unassigned', // in idea pool!
    occasion: 'christmas',
    targetYear: 2026,
    type: 'handmade',
    status: 'idea',
    priority: 'low',
    estimatedPrice: 25,
    craftingHoursEstimated: 2,
    craftDifficulty: 'Easy',
    craftSupplies: [
      { id: 'sup-o1', name: 'Swing-top glass cruet bottles (pack of 4)', estimatedCost: 14, purchased: false },
      { id: 'sup-o2', name: 'Single-estate extra virgin cold pressed olive oil (1L)', estimatedCost: 18, purchased: false },
      { id: 'sup-o3', name: 'Fresh organic rosemary sprigs & crushed pink peppercorns', estimatedCost: 5, purchased: false },
    ],
    notes: 'Great scalable holiday gift idea for coworkers or neighbors! Takes just 2 hours to infuse and bottle.',
    createdAt: '2026-09-02T12:00:00Z',
  },
  {
    id: 'gift-7',
    title: 'Cozy Merino Wool Knit Beanie',
    recipientId: 'person-1',
    occasion: 'christmas',
    targetYear: 2026,
    type: 'handmade',
    status: 'planning',
    priority: 'medium',
    estimatedPrice: 22,
    craftingHoursEstimated: 7,
    craftDifficulty: 'Medium',
    craftSupplies: [
      { id: 'sup-w1', name: '2 skeins Malabrigo Rios pure merino yarn (Forest green)', estimatedCost: 28, purchased: false },
      { id: 'sup-w2', name: 'Handmade vegan leather clip-on tag', estimatedCost: 4, purchased: false },
    ],
    notes: 'Start in November so it can be ready before ski trip in December.',
    createdAt: '2026-09-03T15:00:00Z',
  },
];

export const DEFAULT_HOLIDAYS: HolidayDefinition[] = [
  {
    id: 'hol-val',
    name: "Valentine's Day",
    month: 2,
    day: 14,
    defaultEnabled: true,
    iconName: 'Heart',
    description: 'Celebrate partners, loved ones, and close friends',
  },
  {
    id: 'hol-mom',
    name: "Mother's Day",
    month: 5,
    day: 10,
    defaultEnabled: true,
    iconName: 'Sun',
    description: 'Honor moms, grandmothers, and mother figures',
  },
  {
    id: 'hol-dad',
    name: "Father's Day",
    month: 6,
    day: 21,
    defaultEnabled: true,
    iconName: 'Smile',
    description: 'Honor dads and father figures',
  },
  {
    id: 'hol-hal',
    name: 'Halloween',
    month: 10,
    day: 31,
    defaultEnabled: true,
    iconName: 'Ghost',
    description: 'Costumes, treats, and autumn festivities',
  },
  {
    id: 'hol-xmas',
    name: 'Christmas / Winter Holidays',
    month: 12,
    day: 25,
    defaultEnabled: true,
    iconName: 'Gift',
    description: 'The major holiday gift-giving season',
  },
  {
    id: 'hol-ny',
    name: "New Year's Day",
    month: 1,
    day: 1,
    defaultEnabled: true,
    iconName: 'Sparkles',
    description: 'Ring in the new year with gifts of good fortune',
  },
];
